/** 제품 런타임과 분리해 보관하는 MatrAIx 최소 스냅샷이다. */
export const MATRAIX_SOURCE = {
  repository: "https://github.com/MatrAIx-ai/MatrAIx-Persona-8B",
  commit: "3202a0bf6134776735c4ab4d50de79be8c6a5e8b",
  dimensionSchemaSha: "742a50ed79f106675311c09f016fff48951f841c",
} as const;

export const MATRAIX_DIMENSION_IDS = [
  "age_bracket",
  "tech_savviness",
  "skill_investing",
  "risk_tolerance",
  "decision_style",
  "learning_style",
  "big5_anxiety",
  "cog_patience",
  "cog_ambiguity_tolerance",
  "cog_attention_span",
  "cog_decision_speed",
  "cog_confidence_calibration",
  "health_stress_level",
  "health_cognitive_load_capacity",
  "trait_self_regulation",
] as const;

export type MatrAIxDimensionId = (typeof MATRAIX_DIMENSION_IDS)[number];

export type MatrAIxChildPersona = {
  personaId: string;
  source: "real_human_survey" | "synthetic";
  sourcePath: string;
  dimensions: Record<MatrAIxDimensionId, string>;
};

const samplePath = (personaId: string) =>
  `persona/datasets/matraix-persona-dev-sample/persona_${personaId}.yaml`;

/**
 * MatrAIx 개발 표본에서 신호 해석에 필요한 차원만 최소 스냅샷했다.
 * 이름·성별·지역·언어는 이 평가에 필요하지 않아 복사하지 않는다.
 */
export const MATRAIX_CHILD_PERSONAS: readonly MatrAIxChildPersona[] = [
  {
    personaId: "0151",
    source: "real_human_survey",
    sourcePath: samplePath("0151"),
    dimensions: {
      age_bracket: "13-17",
      tech_savviness: "Digital native",
      skill_investing: "Beginner",
      risk_tolerance: "Balanced",
      decision_style: "Deliberative",
      learning_style: "Mixed",
      big5_anxiety: "Very high",
      cog_patience: "High",
      cog_ambiguity_tolerance: "Low",
      cog_attention_span: "Long",
      cog_decision_speed: "Snap decisions",
      cog_confidence_calibration: "Underconfident",
      health_stress_level: "Moderate",
      health_cognitive_load_capacity: "Moderate",
      trait_self_regulation: "Moderate",
    },
  },
  {
    personaId: "0152",
    source: "real_human_survey",
    sourcePath: samplePath("0152"),
    dimensions: {
      age_bracket: "5-12",
      tech_savviness: "Reluctant",
      skill_investing: "Beginner",
      risk_tolerance: "Balanced",
      decision_style: "Intuitive",
      learning_style: "Visual",
      big5_anxiety: "Average",
      cog_patience: "High",
      cog_ambiguity_tolerance: "Moderate",
      cog_attention_span: "Very short",
      cog_decision_speed: "Quick",
      cog_confidence_calibration: "Well-calibrated",
      health_stress_level: "Moderate",
      health_cognitive_load_capacity: "Moderate",
      trait_self_regulation: "Slight",
    },
  },
  {
    personaId: "0160",
    source: "real_human_survey",
    sourcePath: samplePath("0160"),
    dimensions: {
      age_bracket: "5-12",
      tech_savviness: "Cautious adopter",
      skill_investing: "Beginner",
      risk_tolerance: "Risk-averse",
      decision_style: "Consensus-driven",
      learning_style: "Kinesthetic",
      big5_anxiety: "Low",
      cog_patience: "Low",
      cog_ambiguity_tolerance: "None",
      cog_attention_span: "Very long",
      cog_decision_speed: "Quick",
      cog_confidence_calibration: "Overconfident",
      health_stress_level: "Moderate",
      health_cognitive_load_capacity: "High",
      trait_self_regulation: "Slight",
    },
  },
  {
    personaId: "0165",
    source: "real_human_survey",
    sourcePath: samplePath("0165"),
    dimensions: {
      age_bracket: "5-12",
      tech_savviness: "Reluctant",
      skill_investing: "Intermediate",
      risk_tolerance: "Balanced",
      decision_style: "Consensus-driven",
      learning_style: "Kinesthetic",
      big5_anxiety: "Low",
      cog_patience: "High",
      cog_ambiguity_tolerance: "Moderate",
      cog_attention_span: "Long",
      cog_decision_speed: "Deliberate",
      cog_confidence_calibration: "Overconfident",
      health_stress_level: "Very high",
      health_cognitive_load_capacity: "None",
      trait_self_regulation: "Strong",
    },
  },
  {
    personaId: "0178",
    source: "synthetic",
    sourcePath: samplePath("0178"),
    dimensions: {
      age_bracket: "5-12",
      tech_savviness: "Reluctant",
      skill_investing: "Beginner",
      risk_tolerance: "Risk-averse",
      decision_style: "Intuitive",
      learning_style: "Reading / writing",
      big5_anxiety: "Low",
      cog_patience: "High",
      cog_ambiguity_tolerance: "High",
      cog_attention_span: "Very long",
      cog_decision_speed: "Snap decisions",
      cog_confidence_calibration: "Underconfident",
      health_stress_level: "Very high",
      health_cognitive_load_capacity: "None",
      trait_self_regulation: "Strong",
    },
  },
  {
    personaId: "0182",
    source: "synthetic",
    sourcePath: samplePath("0182"),
    dimensions: {
      age_bracket: "13-17",
      tech_savviness: "Cautious adopter",
      skill_investing: "Intermediate",
      risk_tolerance: "Balanced",
      decision_style: "Analytical",
      learning_style: "Kinesthetic",
      big5_anxiety: "Average",
      cog_patience: "High",
      cog_ambiguity_tolerance: "Moderate",
      cog_attention_span: "Very short",
      cog_decision_speed: "Quick",
      cog_confidence_calibration: "Well-calibrated",
      health_stress_level: "High",
      health_cognitive_load_capacity: "High",
      trait_self_regulation: "Slight",
    },
  },
  {
    personaId: "0185",
    source: "synthetic",
    sourcePath: samplePath("0185"),
    dimensions: {
      age_bracket: "13-17",
      tech_savviness: "Comfortable",
      skill_investing: "Intermediate",
      risk_tolerance: "Risk-tolerant",
      decision_style: "Intuitive",
      learning_style: "Mixed",
      big5_anxiety: "Average",
      cog_patience: "High",
      cog_ambiguity_tolerance: "None",
      cog_attention_span: "Short",
      cog_decision_speed: "Quick",
      cog_confidence_calibration: "Underconfident",
      health_stress_level: "Very high",
      health_cognitive_load_capacity: "Moderate",
      trait_self_regulation: "Moderate",
    },
  },
  {
    personaId: "0189",
    source: "synthetic",
    sourcePath: samplePath("0189"),
    dimensions: {
      age_bracket: "13-17",
      tech_savviness: "Comfortable",
      skill_investing: "Intermediate",
      risk_tolerance: "Risk-averse",
      decision_style: "Consensus-driven",
      learning_style: "Mixed",
      big5_anxiety: "High",
      cog_patience: "None",
      cog_ambiguity_tolerance: "Very high",
      cog_attention_span: "Short",
      cog_decision_speed: "Quick",
      cog_confidence_calibration: "Confident",
      health_stress_level: "Very high",
      health_cognitive_load_capacity: "High",
      trait_self_regulation: "Absent",
    },
  },
  {
    personaId: "0190",
    source: "synthetic",
    sourcePath: samplePath("0190"),
    dimensions: {
      age_bracket: "13-17",
      tech_savviness: "Comfortable",
      skill_investing: "Beginner",
      risk_tolerance: "Cautious",
      decision_style: "Consensus-driven",
      learning_style: "Auditory",
      big5_anxiety: "Average",
      cog_patience: "High",
      cog_ambiguity_tolerance: "High",
      cog_attention_span: "Long",
      cog_decision_speed: "Quick",
      cog_confidence_calibration: "Underconfident",
      health_stress_level: "High",
      health_cognitive_load_capacity: "High",
      trait_self_regulation: "Slight",
    },
  },
  {
    personaId: "0193",
    source: "synthetic",
    sourcePath: samplePath("0193"),
    dimensions: {
      age_bracket: "5-12",
      tech_savviness: "Comfortable",
      skill_investing: "None",
      risk_tolerance: "Risk-averse",
      decision_style: "Intuitive",
      learning_style: "Visual",
      big5_anxiety: "Low",
      cog_patience: "Low",
      cog_ambiguity_tolerance: "Very high",
      cog_attention_span: "Very short",
      cog_decision_speed: "Agonizes",
      cog_confidence_calibration: "Well-calibrated",
      health_stress_level: "High",
      health_cognitive_load_capacity: "High",
      trait_self_regulation: "Strong",
    },
  },
  {
    personaId: "0196",
    source: "synthetic",
    sourcePath: samplePath("0196"),
    dimensions: {
      age_bracket: "5-12",
      tech_savviness: "Cautious adopter",
      skill_investing: "Intermediate",
      risk_tolerance: "Risk-averse",
      decision_style: "Analytical",
      learning_style: "Mixed",
      big5_anxiety: "High",
      cog_patience: "Moderate",
      cog_ambiguity_tolerance: "Low",
      cog_attention_span: "Average",
      cog_decision_speed: "Snap decisions",
      cog_confidence_calibration: "Underconfident",
      health_stress_level: "Very high",
      health_cognitive_load_capacity: "High",
      trait_self_regulation: "Moderate",
    },
  },
  {
    personaId: "0200",
    source: "synthetic",
    sourcePath: samplePath("0200"),
    dimensions: {
      age_bracket: "13-17",
      tech_savviness: "Cautious adopter",
      skill_investing: "Beginner",
      risk_tolerance: "Risk-tolerant",
      decision_style: "Analytical",
      learning_style: "Reading / writing",
      big5_anxiety: "High",
      cog_patience: "Very high",
      cog_ambiguity_tolerance: "Moderate",
      cog_attention_span: "Very long",
      cog_decision_speed: "Snap decisions",
      cog_confidence_calibration: "Cautious",
      health_stress_level: "Very high",
      health_cognitive_load_capacity: "Moderate",
      trait_self_regulation: "Strong",
    },
  },
];

export function getMatrAIxPersona(personaId: string): MatrAIxChildPersona {
  const persona = MATRAIX_CHILD_PERSONAS.find((item) => item.personaId === personaId);
  if (!persona) throw new Error(`Unknown MatrAIx persona: ${personaId}`);
  return persona;
}
