-- 앱 베이스 스키마. 라이브(hero-kiwoom) `public` 스키마를 내성(introspection)으로 복원했다.
--
-- 이 파일이 없던 동안 저장소에는 news_* 마이그레이션과 ALTER 2건만 있어서,
-- 새 환경에서 `supabase db reset` 을 하면 없는 테이블에 ALTER 를 쳐서 실패했다.
-- 그래서 타임스탬프를 news_* 보다 앞에 두고(news_article_stocks 가 stocks 를 참조한다),
-- 내용은 뒤따르는 ALTER 2건이 아직 적용되지 않은 "ALTER 이전 모양"으로 맞춘다.
--
--   20260814052538_stock_tab_views_per_stock_category_count.sql
--     → stock_tab_views 의 duration_seconds/opened_at/closed_at 을 지우고 stock_id/created_at 을 넣는다.
--       따라서 여기서는 앞의 셋만 만들고 뒤의 둘은 만들지 않는다.
--   20260814111455_add_profiles_guardian_role.sql
--     → profiles 에 guardian_role 과 updated_at 을 넣는다.
--       따라서 여기서는 둘 다 만들지 않는다. profiles_set_updated_at 트리거는
--       그 마이그레이션의 주석대로 updated_at 컬럼보다 먼저 존재했으므로 여기서 만든다.
--
-- 라이브에는 이미 이 스키마가 있으므로 적용하지 말고 이력만 등록한다. supabase/migrations/README.md 참고.

begin;

-- 가족 구성원. login_id/login_password 로 로그인하고 auth.users 연동은 선택이다.
create table public.profiles (
  id bigint generated by default as identity,
  name text not null,
  login_id text not null,
  login_password text not null,
  parent_child text not null,
  family_tag text not null,
  auth_user_id uuid,
  constraint profiles_pkey primary key (id),
  constraint profiles_login_id_unique unique (login_id),
  constraint profiles_auth_user_id_key unique (auth_user_id),
  constraint profiles_auth_user_id_fkey foreign key (auth_user_id) references auth.users (id) on delete cascade,
  -- 컬럼은 not null 이지만 체크는 null 을 허용한다. 라이브와 같은 모양으로 둔다.
  constraint profiles_parent_child_check
    check (parent_child = any (array['parent'::text, 'child'::text]) or parent_child is null)
);

-- 51종 투자 유니버스. stock_id 는 시퀀스 없이 적재 스크립트가 직접 넣는다.
create table public.stocks (
  stock_name text not null,
  stock_code text not null,
  category text not null,
  stock_id integer not null,
  constraint stocks_stock_id_pk primary key (stock_id),
  constraint stocks_stock_name_key unique (stock_name),
  constraint stocks_stock_code_key unique (stock_code)
);

-- 기본키와 겹치는 라이브 잔재다. 스키마 대조에서 차이로 잡히지 않게 그대로 만든다.
-- create table 안에 두면 PostgreSQL 이 기본키와 같은 정의로 보고 지워버리므로 따로 붙인다.
alter table public.stocks add constraint stocks_stock_id_unique unique (stock_id);

create index idx_stocks_stock_name on public.stocks using btree (stock_name);

-- 투자 유니버스 51종은 스키마가 아니라 참조 데이터지만, 이 표가 비면 apply_trade·holdings·
-- stock_candles·news_article_stocks 가 모두 붙을 곳이 없고 seed.sql 의 뉴스 주체 연결도 끊긴다.
-- 라이브 값을 그대로 옮겨 새 환경에서도 같은 stock_id 를 쓰게 한다.
insert into public.stocks (stock_id, stock_name, stock_code, category) values
  (1, '삼양식품', '003230', '식품'),
  (2, '크래프톤', '259960', '게임'),
  (3, '오리온', '271560', '식품'),
  (4, 'NC', '036570', '게임'),
  (5, '하이브', '352820', '엔터'),
  (6, '기아', '000270', '자동차'),
  (7, '삼성전자', '005930', '반도체·전자'),
  (8, '현대차', '005380', '자동차'),
  (9, '에이피알', '278470', '화장품'),
  (10, 'CJ제일제당', '097950', '식품'),
  (11, '넷마블', '251270', '게임'),
  (12, '코웨이', '021240', '유통'),
  (13, '농심', '004370', '식품'),
  (14, 'LG전자', '066570', '반도체·전자'),
  (15, '에스엠', '041510', '엔터'),
  (16, 'JYP Ent.', '035900', '엔터'),
  (17, '더블유게임즈', '192080', '게임'),
  (18, '아모레퍼시픽', '090430', '화장품'),
  (19, '달바글로벌', '483650', '화장품'),
  (20, 'LG생활건강', '051900', '화장품'),
  (21, '대한항공', '003490', '항공'),
  (22, '와이지엔터테인먼트', '122870', '엔터'),
  (23, '현대로템', '064350', '방산'),
  (24, '롯데렌탈', '089860', '유통'),
  (25, 'KB금융', '105560', '은행·금융'),
  (26, '신한지주', '055550', '은행·금융'),
  (27, '하나금융지주', '086790', '은행·금융'),
  (28, '한국전력', '015760', '에너지'),
  (29, '신세계', '004170', '유통'),
  (30, '우리금융지주', '316140', '은행·금융'),
  (31, 'BGF리테일', '282330', '유통'),
  (32, 'S-Oil', '010950', '에너지'),
  (33, 'GS', '078930', '에너지'),
  (34, '키움증권', '039490', '은행·금융'),
  (35, 'SK이노베이션', '096770', '에너지'),
  (36, 'CJ대한통운', '000120', '물류'),
  (37, 'HD현대중공업', '329180', '조선'),
  (38, 'HD한국조선해양', '009540', '조선'),
  (39, '한화에어로스페이스', '012450', '방산'),
  (40, 'SK하이닉스', '000660', '반도체·전자'),
  (41, '현대모비스', '012330', '자동차'),
  (42, 'HMM', '011200', '물류'),
  (43, '현대글로비스', '086280', '물류'),
  (44, '아시아나항공', '020560', '항공'),
  (45, '한진칼', '180640', '항공'),
  (46, 'LIG디펜스앤에어로스페이스', '079550', '방산'),
  (47, 'SK스퀘어', '402340', '반도체·전자'),
  (48, '한화오션', '042660', '조선'),
  (49, '삼성중공업', '010140', '조선'),
  (50, '포스코인터내셔널', '047050', '물류'),
  (51, '한국항공우주', '047810', '방산')
on conflict (stock_id) do nothing;

-- 구성원별 현금 잔고. apply_trade 가 없으면 만들어 쓴다.
create table public.account (
  user_id bigint not null,
  balance numeric not null default 10000000,
  constraint account_pkey primary key (user_id),
  constraint account_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade
);

create table public.transactions (
  id uuid not null default gen_random_uuid(),
  user_id bigint not null,
  trade_price numeric not null,
  trade_quantity numeric not null,
  trade_reason text not null,
  side text not null default 'buy'::text,
  created_at timestamptz not null default now(),
  realized_profit integer,
  stock_id integer not null,
  constraint transactions_pkey primary key (id),
  constraint transactions_side_check check (side = any (array['buy'::text, 'sell'::text])),
  constraint transactions_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint transactions_stock_id_int_fkey foreign key (stock_id) references public.stocks (stock_id)
);

create index idx_transactions_user_id on public.transactions using btree (user_id);
create index idx_transactions_created_at on public.transactions using btree (created_at);

create table public.holdings (
  user_id bigint not null,
  stock_id integer not null,
  quantity numeric not null default 0,
  avg_price numeric not null default 0,
  updated_at timestamptz not null default now(),
  constraint holdings_pkey primary key (user_id, stock_id),
  constraint holdings_quantity_check check (quantity >= 0),
  constraint holdings_avg_price_check check (avg_price >= 0),
  constraint holdings_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint holdings_stock_id_fkey foreign key (stock_id) references public.stocks (stock_id)
);

create index idx_holdings_user on public.holdings using btree (user_id);

-- 종목 상세 체류 기록(ALTER 이전 모양). 당시 프론트는 구간의 시작·끝 시각을 보냈고
-- duration_seconds 는 서버가 계산하는 생성 컬럼이라 요청에 담기지 않았다.
-- 컬럼 셋은 20260814052538 이 지워서 라이브에서 원래 타입을 다시 읽을 수 없다.
-- 뒤의 ALTER 가 그대로 드롭할 수 있는 모양이면 충분하므로 당시 route handler 가 보내던 값에 맞춘다.
create table public.stock_tab_views (
  id uuid not null default gen_random_uuid(),
  user_id bigint not null,
  opened_at timestamptz not null,
  closed_at timestamptz not null,
  duration_seconds numeric generated always as (extract(epoch from (closed_at - opened_at))) stored,
  tab_count integer not null default 0,
  constraint stock_tab_views_pkey primary key (id),
  constraint stock_tab_views_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade
);

create index stock_tab_views_user_id_idx on public.stock_tab_views using btree (user_id);

create table public.stock_candles (
  stock_id integer not null,
  timeframe text not null,
  candle_time timestamptz not null,
  open numeric not null,
  high numeric not null,
  low numeric not null,
  close numeric not null,
  volume bigint not null default 0,
  constraint stock_candles_pkey primary key (stock_id, timeframe, candle_time),
  constraint stock_candles_timeframe_check check (timeframe = any (array['daily'::text, 'weekly'::text])),
  constraint stock_candles_volume_check check (volume >= 0),
  constraint stock_candles_check check (high >= greatest(open, close, low)),
  constraint stock_candles_check1 check (low <= least(open, close, high)),
  constraint stock_candles_stock_id_fkey foreign key (stock_id) references public.stocks (stock_id) on delete cascade
);

create index stock_candles_lookup_idx
  on public.stock_candles using btree (stock_id, timeframe, candle_time desc);

create table public.trade_likes (
  id bigint generated always as identity,
  transaction_id uuid not null,
  user_id bigint not null,
  created_at timestamptz not null default now(),
  constraint trade_likes_pkey primary key (id),
  constraint trade_likes_transaction_id_user_id_key unique (transaction_id, user_id),
  constraint trade_likes_transaction_id_fkey foreign key (transaction_id) references public.transactions (id) on delete cascade,
  constraint trade_likes_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade
);

create index trade_likes_transaction_idx on public.trade_likes using btree (transaction_id);

create table public.trade_comments (
  id bigint generated always as identity,
  transaction_id uuid not null,
  user_id bigint not null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint trade_comments_pkey primary key (id),
  constraint trade_comments_body_check check (char_length(btrim(body)) >= 1 and char_length(btrim(body)) <= 200),
  constraint trade_comments_transaction_id_fkey foreign key (transaction_id) references public.transactions (id) on delete cascade,
  constraint trade_comments_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade
);

create index trade_comments_transaction_idx on public.trade_comments using btree (transaction_id, created_at);

-- profiles.updated_at 은 20260814111455 가 추가한다. 트리거가 먼저 있던 라이브 순서를 유지한다.
create function public.set_updated_at()
returns trigger
language plpgsql
set search_path to 'pg_catalog', 'public'
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- 잔고·보유·거래기록을 한 트랜잭션에서 갱신한다. web/app/api/trade 가 callRpc 로 호출한다.
create function public.apply_trade(
  p_user_id bigint,
  p_stock_code text,
  p_side text,
  p_price numeric,
  p_quantity numeric,
  p_reason text default null::text
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_stock_id integer;
  v_balance  numeric;
  v_qty      numeric;
  v_avg      numeric;
  v_amount   numeric;
  v_realized integer := null;
  v_tx_id    uuid;
begin
  if p_side not in ('buy', 'sell') then
    raise exception '알 수 없는 주문 방향입니다: %', p_side;
  end if;
  if p_price is null or p_price <= 0 or p_quantity is null or p_quantity <= 0 then
    raise exception '가격과 수량은 0보다 커야 합니다.';
  end if;

  select stock_id into v_stock_id from stocks where stock_code = p_stock_code;
  if v_stock_id is null then
    raise exception '등록되지 않은 종목입니다: %', p_stock_code;
  end if;

  insert into account (user_id) values (p_user_id) on conflict (user_id) do nothing;
  select balance into v_balance from account where user_id = p_user_id for update;

  select quantity, avg_price into v_qty, v_avg
    from holdings where user_id = p_user_id and stock_id = v_stock_id for update;
  v_qty := coalesce(v_qty, 0);
  v_avg := coalesce(v_avg, 0);

  v_amount := p_price * p_quantity;

  if p_side = 'buy' then
    if v_balance < v_amount then
      raise exception '잔액이 부족합니다.';
    end if;
    v_balance := v_balance - v_amount;
    insert into holdings (user_id, stock_id, quantity, avg_price)
      values (p_user_id, v_stock_id, p_quantity, p_price)
      on conflict (user_id, stock_id) do update
        set avg_price  = (holdings.avg_price * holdings.quantity
                          + excluded.avg_price * excluded.quantity)
                         / (holdings.quantity + excluded.quantity),
            quantity   = holdings.quantity + excluded.quantity,
            updated_at = now();
  else
    if v_qty < p_quantity then
      raise exception '보유 수량이 부족합니다.';
    end if;
    v_balance := v_balance + v_amount;
    v_realized := round((p_price - v_avg) * p_quantity);
    if v_qty = p_quantity then
      delete from holdings where user_id = p_user_id and stock_id = v_stock_id;
    else
      update holdings set quantity = v_qty - p_quantity, updated_at = now()
        where user_id = p_user_id and stock_id = v_stock_id;
    end if;
  end if;

  update account set balance = v_balance where user_id = p_user_id;

  insert into transactions
    (user_id, stock_id, side, trade_price, trade_quantity, trade_reason, realized_profit)
  values
    (p_user_id, v_stock_id, p_side, p_price, p_quantity, p_reason, v_realized)
  returning id into v_tx_id;

  return json_build_object(
    'transaction_id',  v_tx_id,
    'balance',         v_balance,
    'realized_profit', v_realized
  );
end;
$$;

-- 앱 서버는 서비스 키로만 붙어 RLS 를 우회한다. 아래 정책은 anon/authenticated 열람 경계다.
alter table public.profiles enable row level security;
alter table public.stocks enable row level security;
alter table public.account enable row level security;
alter table public.transactions enable row level security;
alter table public.holdings enable row level security;
alter table public.stock_tab_views enable row level security;
alter table public.stock_candles enable row level security;
alter table public.trade_likes enable row level security;
alter table public.trade_comments enable row level security;

create policy "Profiles select (own)" on public.profiles
  for select to authenticated using ((select auth.uid()) = auth_user_id);
create policy "Profiles insert (own)" on public.profiles
  for insert to authenticated with check ((select auth.uid()) = auth_user_id);
create policy "Profiles update (own)" on public.profiles
  for update to authenticated using ((select auth.uid()) = auth_user_id)
  with check ((select auth.uid()) = auth_user_id);
create policy "Profiles delete (own)" on public.profiles
  for delete to authenticated using ((select auth.uid()) = auth_user_id);

create policy "Stocks select (authenticated)" on public.stocks
  for select to authenticated using (true);

create policy "Account read own" on public.account
  for select to authenticated using (
    exists (
      select 1 from public.profiles p
      where p.id = account.user_id and p.auth_user_id = (select auth.uid())
    )
  );

create policy "Holdings read own" on public.holdings
  for select to authenticated using (
    user_id in (select profiles.id from public.profiles where profiles.auth_user_id = auth.uid())
  );

create policy "Transactions select (own)" on public.transactions
  for select to authenticated using (
    exists (
      select 1 from public.profiles p
      where p.id = transactions.user_id and p.auth_user_id = (select auth.uid())
    )
  );
create policy "Transactions insert (own)" on public.transactions
  for insert to authenticated with check (
    exists (
      select 1 from public.profiles p
      where p.id = transactions.user_id and p.auth_user_id = (select auth.uid())
    )
  );
create policy "Transactions update (own)" on public.transactions
  for update to authenticated using (
    exists (
      select 1 from public.profiles p
      where p.id = transactions.user_id and p.auth_user_id = (select auth.uid())
    )
  ) with check (
    exists (
      select 1 from public.profiles p
      where p.id = transactions.user_id and p.auth_user_id = (select auth.uid())
    )
  );
create policy "Transactions delete (own)" on public.transactions
  for delete to authenticated using (
    exists (
      select 1 from public.profiles p
      where p.id = transactions.user_id and p.auth_user_id = (select auth.uid())
    )
  );

create policy "Users can insert own tab views" on public.stock_tab_views
  for insert to authenticated with check (
    exists (
      select 1 from public.profiles p
      where p.id = stock_tab_views.user_id and p.auth_user_id = (select auth.uid())
    )
  );
create policy "Users can update own tab views" on public.stock_tab_views
  for update to authenticated using (
    exists (
      select 1 from public.profiles p
      where p.id = stock_tab_views.user_id and p.auth_user_id = (select auth.uid())
    )
  ) with check (
    exists (
      select 1 from public.profiles p
      where p.id = stock_tab_views.user_id and p.auth_user_id = (select auth.uid())
    )
  );

create policy "Stock candles are readable" on public.stock_candles
  for select to anon, authenticated using (true);

-- 시세 캔들은 적재 배치(service_role)만 쓰고 클라이언트는 읽기만 한다.
revoke all on table public.stock_candles from anon, authenticated;
grant select on table public.stock_candles to anon, authenticated;

commit;
